name: Render and publish SST report
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "tidyverse", "rerddap", "giscoR", "patchwork", "ggsci"))
        shell: Rscript {0}

      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("sea_temps_ppb.Rmd", output_file = "docs/index.html")'

      - name: Commit updated data and HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add bay.Rdata coast.Rdata docs/index.html
          git diff --staged --quiet || git commit -m "Daily update"
          git push